using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1300", Justification = "disable", Scope = "namespaceanddescendants", Target = "~T:OpenTK.Utilities.Images.ImageCore")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1307", Justification = "disable", Scope = "namespaceanddescendants", Target = "~T:OpenTK.Utilities.Images.ImageCore")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1309", Justification = "disable", Scope = "namespaceanddescendants", Target = "~T:OpenTK.Utilities.Images.ImageCore")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1310", Justification = "disable", Scope = "namespaceanddescendants", Target = "~T:OpenTK.Utilities.Images.ImageCore")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1311", Justification = "disable", Scope = "namespaceanddescendants", Target = "~T:OpenTK.Utilities.Images.ImageCore")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1401", Justification = "disable", Scope = "namespaceanddescendants", Target = "~T:OpenTK.Utilities.Images.ImageCore")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1407", Justification = "disable", Scope = "namespaceanddescendants", Target = "~T:OpenTK.Utilities.Images.ImageCore")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1101", Justification = "disable", Scope = "namespaceanddescendants", Target = "~T:OpenTK.Utilities.Images.ImageCore")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1516", Justification = "disable", Scope = "namespaceanddescendants", Target = "~T:OpenTK.Utilities.Images.ImageCore")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1503", Justification = "disable", Scope = "namespaceanddescendants", Target = "~T:OpenTK.Utilities.Images.ImageCore")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1519", Justification = "disable", Scope = "namespaceanddescendants", Target = "~T:OpenTK.Utilities.Images.ImageCore")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1312", Justification = "disable", Scope = "namespaceanddescendants", Target = "~T:OpenTK.Utilities.Images.ImageCore")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1129", Justification = "disable", Scope = "namespaceanddescendants", Target = "~T:OpenTK.Utilities.Images.ImageCore")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1023", Justification = "disable", Scope = "namespaceanddescendants", Target = "~T:OpenTK.Utilities.Images.ImageCore")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1139", Justification = "disable", Scope = "namespaceanddescendants", Target = "~T:OpenTK.Utilities.Images.ImageCore")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1027", Justification = "disable", Scope = "namespaceanddescendants", Target = "~T:OpenTK.Utilities.Images.ImageCore")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1208", Justification = "disable", Scope = "namespaceanddescendants", Target = "~T:OpenTK.Utilities.Images.ImageCore")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1518", Justification = "disable", Scope = "namespaceanddescendants", Target = "~T:OpenTK.Utilities.Images.ImageCore")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1413", Justification = "disable", Scope = "namespaceanddescendants", Target = "~T:OpenTK.Utilities.Images.ImageCore")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1201", Justification = "disable", Scope = "namespaceanddescendants", Target = "~T:OpenTK.Utilities.Images.ImageCore")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1402", Justification = "disable", Scope = "namespaceanddescendants", Target = "~T:OpenTK.Utilities.Images.ImageCore")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1507", Justification = "disable", Scope = "namespaceanddescendants", Target = "~T:OpenTK.Utilities.Images.ImageCore")]
